# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ develop ]


  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
            distribution: 'adopt' 
            java-version: '8'

      # Runs a single command using the runners shell
      - name: Build Plugin
        working-directory: ./master
        run: mvn clean verify

